version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -l INFO -c 8

    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
    redis_data:
